version: "3.7"

volumes:
  sbtuser:

services:
  book_server: #container name
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/opt/book-api
      - sbtuser:/home/sbtuser
    ports:
      - 9000:9000
    command:
      - run
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: scalabooksdb
      MYSQL_ROOT_PASSWORD: root
