version: "3.7"

services:
  book_server: #container name
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/opt/book-api
    ports: 
      - 9000:9000
    environment: 
      - DATABASE_URL=jdbc:mysql://localhost/scalabooksdb?useSSL=false
    command: 
      - run
    depends_on: 
      - db
  
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_DATABASE: scalabooksdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USERNAME: username
